# Generated by Django 5.1.6 on 2025-03-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gaming_interests',
            field=models.TextField(blank=True, help_text='List your favorite games or genres.', null=True),
        ),
    ]
